import type { Metadata } from "next";
import { alegreya_sans_font } from '@/ui/fonts';
import "@/ui/css/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${alegreya_sans_font.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
